---
- name: Create kubernetes manifests config directory
  file:
    path: "{{ kube.manifests_dir }}"
    state: directory
  when: haproxy.enabled

- name: Write etcd static pod files
  template:
    src: etcd.yaml.j2
    dest: "{{ kube.manifests_dir }}/etcd.yaml"
  register: etcd_yaml

